### creat report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Ford",
    "model": "Fiesta",
    "year": 2012,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 25000
}

### approved a report 
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": false
}