### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}

### Sign in user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}

### sign out
POST http://localhost:3000/auth/signout

### current user
GET http://localhost:3000/auth/currentuser


### findOne user by id
GET http://localhost:3000/auth/1


### find all user by email 
GET http://localhost:3000/auth?email=test2@test2.com

### delete a user by id

DELETE http://localhost:3000/auth/2


### update user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "password": "testtestetst"
}